# Generated by Django 4.0.6 on 2022-07-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreEmpresa', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=100)),
                ('NIT', models.PositiveIntegerField()),
                ('Telefono', models.PositiveIntegerField()),
            ],
        ),
    ]
