# Generated by Django 4.0.6 on 2022-07-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='NIT',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Telefono',
            field=models.CharField(max_length=10),
        ),
    ]
